export enum ConsentPurpose {
  DOCUMENT_UPLOAD = 'DOCUMENT_UPLOAD',
  AI_ANALYSIS = 'AI_ANALYSIS',
  CLINIC_SHARING = 'CLINIC_SHARING',
  MEDICATION_FOLLOW_UP = 'MEDICATION_FOLLOW_UP',
  MARKETING = 'MARKETING',
}
